<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="6" time="0.066" timestamp="2021-06-24T21:22:08.925374" hostname="Yoshioris-MacBook-Pro.local"><testcase classname="tests.funcs3_test" name="test_func4" file="tests/funcs3_test.py" line="0" time="0.001" /><testcase classname="tests.funcs3_test" name="test_func5" file="tests/funcs3_test.py" line="3" time="0.001"><failure message="assert 1 == False">def test_func5():
  &gt;       assert 1 == False
  E       assert 1 == False

  tests/funcs3_test.py:5: AssertionError</failure></testcase><testcase classname="tests.test_funcs1" name="test_func1" file="tests/test_funcs1.py" line="0" time="0.000" /><testcase classname="tests.test_funcs1" name="test_func2" file="tests/test_funcs1.py" line="3" time="0.001"><failure message="assert 1 == False">def test_func2():
  &gt;       assert 1 == False
  E       assert 1 == False

  tests/test_funcs1.py:5: AssertionError</failure></testcase><testcase classname="tests.test_funcs2" name="test_func3" file="tests/test_funcs2.py" line="0" time="0.000" /><testcase classname="tests.test_funcs2" name="test_func4" file="tests/test_funcs2.py" line="3" time="0.000" /></testsuite></testsuites>
